version: 0.2

env:
  variables:
    AWS_REGION: us-west-1
    ACCOUNT_ID: "167611893883"
    REPO: "springboot-aws-deploy"
    IMAGE: "$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO"

phases:
  install:
    runtime-versions:
      java: corretto17
      docker: 20
    commands:
      - echo "Using Java and Docker in CodeBuild standard image"
      - mvn -v || true
      - docker version || true

  pre_build:
    commands:
      - set -euxo pipefail
      - echo "Caller identity (verifies IAM permissions):"
      - aws sts get-caller-identity
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" > /tmp/ecr.pass
      - test -s /tmp/ecr.pass && echo "Got ECR password (non-empty)"
      - docker login --username AWS --password-stdin "$IMAGE" < /tmp/ecr.pass
      - echo "Ensuring repo exists (idempotent):"
      - aws ecr describe-repositories --repository-names "$REPO" --region "$AWS_REGION" || \
        aws ecr create-repository --repository-name "$REPO" --region "$AWS_REGION"

  build:
    commands:
      - echo "Building app JAR with Maven..."
      - mvn -B -DskipTests package
      - echo "Building Docker image..."
      - COMMIT_SHA=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - docker build -t "$IMAGE:latest" -t "$IMAGE:$COMMIT_SHA" .
      - docker images | head -n 10

  post_build:
    commands:
      - echo "Pushing images to ECR..."
      - docker push "$IMAGE:latest"
      - docker push "$IMAGE:$COMMIT_SHA"
artifacts:
  files:
    - '**/*'
  discard-paths: no
